#pragma once

#include "../../useful/useful.h"
namespace app::lua_bind {
    namespace ControlModule {
        u64 get_stick_angle(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind35ControlModule__get_stick_angle_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_stick_dir(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind33ControlModule__get_stick_dir_implEPNS_26BattleObjectModuleAccessorE");
        bool is_stick_side(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind33ControlModule__is_stick_side_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_sub_stick_dir(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind37ControlModule__get_sub_stick_dir_implEPNS_26BattleObjectModuleAccessorE");
        bool is_sub_stickSide(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind36ControlModule__is_sub_stickSide_implEPNS_26BattleObjectModuleAccessorE");
        bool is_enable_flick_jump(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind40ControlModule__is_enable_flick_jump_implEPNS_26BattleObjectModuleAccessorE");
        u64 start_clatter(app::BattleObjectModuleAccessor *,float,float,float,signed char,int,bool,bool) asm("_ZN3app8lua_bind33ControlModule__start_clatter_implEPNS_26BattleObjectModuleAccessorEfffaibb");
        void set_dec_time(app::BattleObjectModuleAccessor *,float,int) asm("_ZN3app8lua_bind32ControlModule__set_dec_time_implEPNS_26BattleObjectModuleAccessorEfi");
        void set_dec_time_recovery(app::BattleObjectModuleAccessor *,float,int) asm("_ZN3app8lua_bind41ControlModule__set_dec_time_recovery_implEPNS_26BattleObjectModuleAccessorEfi");
        void set_clatter_time(app::BattleObjectModuleAccessor *,float,int) asm("_ZN3app8lua_bind36ControlModule__set_clatter_time_implEPNS_26BattleObjectModuleAccessorEfi");
        u64 add_clatter_time(app::BattleObjectModuleAccessor *,float,int) asm("_ZN3app8lua_bind36ControlModule__add_clatter_time_implEPNS_26BattleObjectModuleAccessorEfi");
        u64 get_clatter_time(app::BattleObjectModuleAccessor *,int) asm("_ZN3app8lua_bind36ControlModule__get_clatter_time_implEPNS_26BattleObjectModuleAccessorEi");
        void set_clatter_stop(app::BattleObjectModuleAccessor *,bool) asm("_ZN3app8lua_bind36ControlModule__set_clatter_stop_implEPNS_26BattleObjectModuleAccessorEb");
        bool is_clatter_stop(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind35ControlModule__is_clatter_stop_implEPNS_26BattleObjectModuleAccessorE");
        u64 start_clatter_motion_rate(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind45ControlModule__start_clatter_motion_rate_implEPNS_26BattleObjectModuleAccessorE");
        u64 end_clatter_motion_rate(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind43ControlModule__end_clatter_motion_rate_implEPNS_26BattleObjectModuleAccessorE");
        u64 end_clatter(app::BattleObjectModuleAccessor *,int) asm("_ZN3app8lua_bind31ControlModule__end_clatter_implEPNS_26BattleObjectModuleAccessorEi");
        bool is_input_clatter(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind36ControlModule__is_input_clatter_implEPNS_26BattleObjectModuleAccessorE");
        void set_clatter_shake_scale(app::BattleObjectModuleAccessor *,float) asm("_ZN3app8lua_bind43ControlModule__set_clatter_shake_scale_implEPNS_26BattleObjectModuleAccessorEf");
        u64 reset_button(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind32ControlModule__reset_button_implEPNS_26BattleObjectModuleAccessorE");
        u64 reset_trigger(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind33ControlModule__reset_trigger_implEPNS_26BattleObjectModuleAccessorE");
        u64 reset_trigger_2(app::BattleObjectModuleAccessor *,int) asm("_ZN3app8lua_bind35ControlModule__reset_trigger_2_implEPNS_26BattleObjectModuleAccessorEi");
        u64 reset_main_stick_x(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind38ControlModule__reset_main_stick_x_implEPNS_26BattleObjectModuleAccessorE");
        void set_main_stick_x(app::BattleObjectModuleAccessor *,float) asm("_ZN3app8lua_bind36ControlModule__set_main_stick_x_implEPNS_26BattleObjectModuleAccessorEf");
        u64 reset_main_stick_y(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind38ControlModule__reset_main_stick_y_implEPNS_26BattleObjectModuleAccessorE");
        void set_main_stick_y(app::BattleObjectModuleAccessor *,float) asm("_ZN3app8lua_bind36ControlModule__set_main_stick_y_implEPNS_26BattleObjectModuleAccessorEf");
        u64 reset_main_stick(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind36ControlModule__reset_main_stick_implEPNS_26BattleObjectModuleAccessorE");
        u64 reset_sub_stick_x(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind37ControlModule__reset_sub_stick_x_implEPNS_26BattleObjectModuleAccessorE");
        u64 reset_sub_stick_y(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind37ControlModule__reset_sub_stick_y_implEPNS_26BattleObjectModuleAccessorE");
        u64 reset_sub_stick(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind35ControlModule__reset_sub_stick_implEPNS_26BattleObjectModuleAccessorE");
        u64 reset_flick_x(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind33ControlModule__reset_flick_x_implEPNS_26BattleObjectModuleAccessorE");
        u64 reset_flick_y(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind33ControlModule__reset_flick_y_implEPNS_26BattleObjectModuleAccessorE");
        u64 reset_flick_sub_x(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind37ControlModule__reset_flick_sub_x_implEPNS_26BattleObjectModuleAccessorE");
        u64 reset_flick_sub_y(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind37ControlModule__reset_flick_sub_y_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_stick_x(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind31ControlModule__get_stick_x_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_stick_prev_x(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind36ControlModule__get_stick_prev_x_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_stick_y(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind31ControlModule__get_stick_y_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_stick_prev_y(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind36ControlModule__get_stick_prev_y_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_flick_x(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind31ControlModule__get_flick_x_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_flick_x_dir(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind35ControlModule__get_flick_x_dir_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_flick_y(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind31ControlModule__get_flick_y_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_flick_y_dir(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind35ControlModule__get_flick_y_dir_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_flick_no_reset_x(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind40ControlModule__get_flick_no_reset_x_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_flick_no_reset_y(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind40ControlModule__get_flick_no_reset_y_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_flick_after_x(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind37ControlModule__get_flick_after_x_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_flick_after_x_dir(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind41ControlModule__get_flick_after_x_dir_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_flick_after_y(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind37ControlModule__get_flick_after_y_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_flick_sub_x(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind35ControlModule__get_flick_sub_x_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_flick_sub_x_dir(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind39ControlModule__get_flick_sub_x_dir_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_flick_sub_y(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind35ControlModule__get_flick_sub_y_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_flick_sub_y_dir(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind39ControlModule__get_flick_sub_y_dir_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_sub_stick_x(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind35ControlModule__get_sub_stick_x_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_sub_stick_prev_x(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind40ControlModule__get_sub_stick_prev_x_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_sub_stick_y(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind35ControlModule__get_sub_stick_y_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_sub_stick_prev_y(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind40ControlModule__get_sub_stick_prev_y_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_trigger(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind31ControlModule__get_trigger_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_trigger_count(app::BattleObjectModuleAccessor *,unsigned char) asm("_ZN3app8lua_bind37ControlModule__get_trigger_count_implEPNS_26BattleObjectModuleAccessorEh");
        u64 get_trigger_count_prev(app::BattleObjectModuleAccessor *,unsigned char) asm("_ZN3app8lua_bind42ControlModule__get_trigger_count_prev_implEPNS_26BattleObjectModuleAccessorEh");
        u64 get_button(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind30ControlModule__get_button_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_button_prev(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind35ControlModule__get_button_prev_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_release(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind31ControlModule__get_release_implEPNS_26BattleObjectModuleAccessorE");
        u64 check_button_trigger(app::BattleObjectModuleAccessor *,int) asm("_ZN3app8lua_bind40ControlModule__check_button_trigger_implEPNS_26BattleObjectModuleAccessorEi");
        u64 check_button_release(app::BattleObjectModuleAccessor *,int) asm("_ZN3app8lua_bind40ControlModule__check_button_release_implEPNS_26BattleObjectModuleAccessorEi");
        u64 check_button_on(app::BattleObjectModuleAccessor *,int) asm("_ZN3app8lua_bind35ControlModule__check_button_on_implEPNS_26BattleObjectModuleAccessorEi");
        u64 check_button_off(app::BattleObjectModuleAccessor *,int) asm("_ZN3app8lua_bind36ControlModule__check_button_off_implEPNS_26BattleObjectModuleAccessorEi");
        u64 check_button_on_trriger(app::BattleObjectModuleAccessor *,int) asm("_ZN3app8lua_bind43ControlModule__check_button_on_trriger_implEPNS_26BattleObjectModuleAccessorEi");
        u64 check_button_on_release(app::BattleObjectModuleAccessor *,int) asm("_ZN3app8lua_bind43ControlModule__check_button_on_release_implEPNS_26BattleObjectModuleAccessorEi");
        void set_off(app::BattleObjectModuleAccessor *,bool) asm("_ZN3app8lua_bind27ControlModule__set_off_implEPNS_26BattleObjectModuleAccessorEb");
        void set_stick_reverse(app::BattleObjectModuleAccessor *,bool,int) asm("_ZN3app8lua_bind37ControlModule__set_stick_reverse_implEPNS_26BattleObjectModuleAccessorEbi");
        bool is_stick_reversed(app::BattleObjectModuleAccessor *,int) asm("_ZN3app8lua_bind37ControlModule__is_stick_reversed_implEPNS_26BattleObjectModuleAccessorEi");
        u64 get_clatter_threshold(app::BattleObjectModuleAccessor *,int) asm("_ZN3app8lua_bind41ControlModule__get_clatter_threshold_implEPNS_26BattleObjectModuleAccessorEi");
        void set_rumble_hit_data(app::BattleObjectModuleAccessor *,phx::Hash40,int,bool,unsigned int,int) asm("_ZN3app8lua_bind39ControlModule__set_rumble_hit_data_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40Eibji");
        u64 clear_rumble_hit_data(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind41ControlModule__clear_rumble_hit_data_implEPNS_26BattleObjectModuleAccessorE");
        u64 request_rumble_hit(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind38ControlModule__request_rumble_hit_implEPNS_26BattleObjectModuleAccessorE");
        void set_rumble(app::BattleObjectModuleAccessor *,phx::Hash40,int,bool,unsigned int) asm("_ZN3app8lua_bind30ControlModule__set_rumble_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40Eibj");
        void set_rumble_all(app::BattleObjectModuleAccessor *,phx::Hash40,int,unsigned int) asm("_ZN3app8lua_bind34ControlModule__set_rumble_all_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40Eij");
        u64 stop_rumble_kind(app::BattleObjectModuleAccessor *,phx::Hash40,unsigned int) asm("_ZN3app8lua_bind36ControlModule__stop_rumble_kind_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40Ej");
        u64 stop_rumble_id(app::BattleObjectModuleAccessor *,unsigned int) asm("_ZN3app8lua_bind34ControlModule__stop_rumble_id_implEPNS_26BattleObjectModuleAccessorEj");
        u64 stop_rumble(app::BattleObjectModuleAccessor *,bool) asm("_ZN3app8lua_bind31ControlModule__stop_rumble_implEPNS_26BattleObjectModuleAccessorEb");
        u64 stop_rumble_all(app::BattleObjectModuleAccessor *,phx::Hash40,unsigned int) asm("_ZN3app8lua_bind35ControlModule__stop_rumble_all_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40Ej");
        void set_reverse_x_frame(app::BattleObjectModuleAccessor *,int,bool) asm("_ZN3app8lua_bind39ControlModule__set_reverse_x_frame_implEPNS_26BattleObjectModuleAccessorEib");
        u64 get_lr(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind26ControlModule__get_lr_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_flick_bonus(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind35ControlModule__get_flick_bonus_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_flick_bonus_lr(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind38ControlModule__get_flick_bonus_lr_implEPNS_26BattleObjectModuleAccessorE");
        u64 reset_flick_bonus(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind37ControlModule__reset_flick_bonus_implEPNS_26BattleObjectModuleAccessorE");
        u64 reset_flick_bonus_lr(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind40ControlModule__reset_flick_bonus_lr_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_stick_x_no_clamp(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind40ControlModule__get_stick_x_no_clamp_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_stick_y_no_clamp(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind40ControlModule__get_stick_y_no_clamp_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_pad_flag(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind32ControlModule__get_pad_flag_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_command_flag_cat(app::BattleObjectModuleAccessor *,int) asm("_ZN3app8lua_bind40ControlModule__get_command_flag_cat_implEPNS_26BattleObjectModuleAccessorEi");
        u64 clear_command(app::BattleObjectModuleAccessor *,bool) asm("_ZN3app8lua_bind33ControlModule__clear_command_implEPNS_26BattleObjectModuleAccessorEb");
        u64 clear_command_one(app::BattleObjectModuleAccessor *,int,int) asm("_ZN3app8lua_bind37ControlModule__clear_command_one_implEPNS_26BattleObjectModuleAccessorEii");
        u64 get_command_life(app::BattleObjectModuleAccessor *,int,int) asm("_ZN3app8lua_bind36ControlModule__get_command_life_implEPNS_26BattleObjectModuleAccessorEii");
        u64 get_command_life_count_max(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind46ControlModule__get_command_life_count_max_implEPNS_26BattleObjectModuleAccessorE");
        void set_command_life_extend(app::BattleObjectModuleAccessor *,unsigned char) asm("_ZN3app8lua_bind43ControlModule__set_command_life_extend_implEPNS_26BattleObjectModuleAccessorEh");
        bool is_clear_command(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind36ControlModule__is_clear_command_implEPNS_26BattleObjectModuleAccessorE");
        u64 exec_command(app::BattleObjectModuleAccessor *,bool) asm("_ZN3app8lua_bind32ControlModule__exec_command_implEPNS_26BattleObjectModuleAccessorEb");
        void set_back_command(app::BattleObjectModuleAccessor *,float) asm("_ZN3app8lua_bind36ControlModule__set_back_command_implEPNS_26BattleObjectModuleAccessorEf");
        u64 reset_turn_lr(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind33ControlModule__reset_turn_lr_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_attack_hi3_fb_kind(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind42ControlModule__get_attack_hi3_fb_kind_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_attack_lw3_fb_kind(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind42ControlModule__get_attack_lw3_fb_kind_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_attack_air_kind(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind39ControlModule__get_attack_air_kind_implEPNS_26BattleObjectModuleAccessorE");
        u64 reset_attack_air_kind(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind41ControlModule__reset_attack_air_kind_implEPNS_26BattleObjectModuleAccessorE");
        void set_attack_air_kind(app::BattleObjectModuleAccessor *,int) asm("_ZN3app8lua_bind39ControlModule__set_attack_air_kind_implEPNS_26BattleObjectModuleAccessorEi");
        u64 get_attack_air_stick_x(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind42ControlModule__get_attack_air_stick_x_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_attack_air_stick_y(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind42ControlModule__get_attack_air_stick_y_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_attack_air_stick_dir(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind44ControlModule__get_attack_air_stick_dir_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_down_stand_fb_kind(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind42ControlModule__get_down_stand_fb_kind_implEPNS_26BattleObjectModuleAccessorE");
        u64 reset_down_stand_fb_kind(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind44ControlModule__reset_down_stand_fb_kind_implEPNS_26BattleObjectModuleAccessorE");
        void set_down_stand_fb_kind(app::BattleObjectModuleAccessor *,int) asm("_ZN3app8lua_bind42ControlModule__set_down_stand_fb_kind_implEPNS_26BattleObjectModuleAccessorEi");
        u64 item_light_throw_fb_kind(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind44ControlModule__item_light_throw_fb_kind_implEPNS_26BattleObjectModuleAccessorE");
        u64 item_light_throw_fb4_kind(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind45ControlModule__item_light_throw_fb4_kind_implEPNS_26BattleObjectModuleAccessorE");
        u64 item_light_throw_air_fb_kind(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind48ControlModule__item_light_throw_air_fb_kind_implEPNS_26BattleObjectModuleAccessorE");
        u64 item_light_throw_air_fb4_kind(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind49ControlModule__item_light_throw_air_fb4_kind_implEPNS_26BattleObjectModuleAccessorE");
        u64 item_heavy_throw_fb_kind(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind44ControlModule__item_heavy_throw_fb_kind_implEPNS_26BattleObjectModuleAccessorE");
        u64 special_s_turn(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind34ControlModule__special_s_turn_implEPNS_26BattleObjectModuleAccessorE");
        bool is_jump_mini_button(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind39ControlModule__is_jump_mini_button_implEPNS_26BattleObjectModuleAccessorE");
        void set_add_jump_mini_button_life(app::BattleObjectModuleAccessor *,signed char) asm("_ZN3app8lua_bind49ControlModule__set_add_jump_mini_button_life_implEPNS_26BattleObjectModuleAccessorEa");
        void set_log_active(app::BattleObjectModuleAccessor *,bool) asm("_ZN3app8lua_bind34ControlModule__set_log_active_implEPNS_26BattleObjectModuleAccessorEb");
        bool is_remake_command(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind37ControlModule__is_remake_command_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_reserve_turn_lr(app::BattleObjectModuleAccessor *,int,int) asm("_ZN3app8lua_bind39ControlModule__get_reserve_turn_lr_implEPNS_26BattleObjectModuleAccessorEii");
        u64 delete_reserve_turn_lr(app::BattleObjectModuleAccessor *,int,int) asm("_ZN3app8lua_bind42ControlModule__delete_reserve_turn_lr_implEPNS_26BattleObjectModuleAccessorEii");
        void set_special_command(app::BattleObjectModuleAccessor *,bool) asm("_ZN3app8lua_bind39ControlModule__set_special_command_implEPNS_26BattleObjectModuleAccessorEb");
        u64 reset_special_command(app::BattleObjectModuleAccessor *,bool) asm("_ZN3app8lua_bind41ControlModule__reset_special_command_implEPNS_26BattleObjectModuleAccessorEb");
        u64 reverse_special_command(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind43ControlModule__reverse_special_command_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_special_command_lr(app::BattleObjectModuleAccessor *,int) asm("_ZN3app8lua_bind42ControlModule__get_special_command_lr_implEPNS_26BattleObjectModuleAccessorEi");
        u64 reverse_x_frame(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind35ControlModule__reverse_x_frame_implEPNS_26BattleObjectModuleAccessorE");
        void set_special_command_life_extend(app::BattleObjectModuleAccessor *,signed char) asm("_ZN3app8lua_bind51ControlModule__set_special_command_life_extend_implEPNS_26BattleObjectModuleAccessorEa");
        void set_special_command_life_count_extend(app::BattleObjectModuleAccessor *,unsigned char) asm("_ZN3app8lua_bind57ControlModule__set_special_command_life_count_extend_implEPNS_26BattleObjectModuleAccessorEh");
    }
}
