#pragma once

#include "../../useful/useful.h"
namespace app::lua_bind {
    namespace EffectModule {
        u64 req(app::BattleObjectModuleAccessor *,phx::Hash40,phx::Vector3f const&,phx::Vector3f const&,float,unsigned int,int,bool,int) asm("_ZN3app8lua_bind22EffectModule__req_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40ERKNS3_8Vector3fES7_fjibi");
        u64 req_2d(app::BattleObjectModuleAccessor *,phx::Hash40,phx::Vector3f const&,phx::Vector3f const&,float,unsigned int) asm("_ZN3app8lua_bind25EffectModule__req_2d_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40ERKNS3_8Vector3fES7_fj");
        u64 req_on_joint(app::BattleObjectModuleAccessor *,phx::Hash40,phx::Hash40,phx::Vector3f const&,phx::Vector3f const&,float,phx::Vector3f const&,phx::Vector3f const&,bool,unsigned int,int,int) asm("_ZN3app8lua_bind31EffectModule__req_on_joint_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40ES4_RKNS3_8Vector3fES7_fS7_S7_bjii");
        u64 req_attach_ground(app::BattleObjectModuleAccessor *,phx::Hash40,app::GroundCollisionLineHandle const&,phx::Vector3f const&,phx::Vector3f const&,float,phx::Vector3f const&,unsigned int,int) asm("_ZN3app8lua_bind36EffectModule__req_attach_ground_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40ERKNS_25GroundCollisionLineHandleERKNS3_8Vector3fESA_fSA_ji");
        u64 req_follow(app::BattleObjectModuleAccessor *,phx::Hash40,phx::Hash40,phx::Vector3f const&,phx::Vector3f const&,float,bool,unsigned int,int,int,int,int,bool,bool) asm("_ZN3app8lua_bind29EffectModule__req_follow_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40ES4_RKNS3_8Vector3fES7_fbjiiiibb");
        u64 req_continual(app::BattleObjectModuleAccessor *,phx::Hash40,phx::Hash40,float,unsigned int,int) asm("_ZN3app8lua_bind32EffectModule__req_continual_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40ES4_fji");
        u64 remove_continual(app::BattleObjectModuleAccessor *,int) asm("_ZN3app8lua_bind35EffectModule__remove_continual_implEPNS_26BattleObjectModuleAccessorEi");
        u64 remove_all_continual(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind39EffectModule__remove_all_continual_implEPNS_26BattleObjectModuleAccessorE");
        u64 req_time(app::BattleObjectModuleAccessor *,phx::Hash40,int,phx::Vector3f const&,phx::Vector3f const&,float,unsigned int,bool,bool) asm("_ZN3app8lua_bind27EffectModule__req_time_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40EiRKNS3_8Vector3fES7_fjbb");
        u64 req_time_follow(app::BattleObjectModuleAccessor *,phx::Hash40,phx::Hash40,int,phx::Vector3f const&,phx::Vector3f const&,float,bool,unsigned int) asm("_ZN3app8lua_bind34EffectModule__req_time_follow_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40ES4_iRKNS3_8Vector3fES7_fbj");
        u64 remove_time(app::BattleObjectModuleAccessor *,phx::Hash40) asm("_ZN3app8lua_bind30EffectModule__remove_time_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40E");
        u64 remove_all_time(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind34EffectModule__remove_all_time_implEPNS_26BattleObjectModuleAccessorE");
        u64 req_emit(app::BattleObjectModuleAccessor *,phx::Hash40,unsigned int) asm("_ZN3app8lua_bind27EffectModule__req_emit_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40Ej");
        u64 remove(app::BattleObjectModuleAccessor *,unsigned int,unsigned int) asm("_ZN3app8lua_bind25EffectModule__remove_implEPNS_26BattleObjectModuleAccessorEjj");
        u64 remove_all(app::BattleObjectModuleAccessor *,unsigned int,unsigned int) asm("_ZN3app8lua_bind29EffectModule__remove_all_implEPNS_26BattleObjectModuleAccessorEjj");
        u64 kill(app::BattleObjectModuleAccessor *,unsigned int,bool,bool) asm("_ZN3app8lua_bind23EffectModule__kill_implEPNS_26BattleObjectModuleAccessorEjbb");
        u64 kill_kind(app::BattleObjectModuleAccessor *,phx::Hash40,bool,bool) asm("_ZN3app8lua_bind28EffectModule__kill_kind_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40Ebb");
        u64 kill_joint_id(app::BattleObjectModuleAccessor *,phx::Hash40,bool,bool) asm("_ZN3app8lua_bind32EffectModule__kill_joint_id_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40Ebb");
        u64 kill_all(app::BattleObjectModuleAccessor *,unsigned int,bool,bool) asm("_ZN3app8lua_bind27EffectModule__kill_all_implEPNS_26BattleObjectModuleAccessorEjbb");
        u64 detach_all(app::BattleObjectModuleAccessor *,unsigned int) asm("_ZN3app8lua_bind29EffectModule__detach_all_implEPNS_26BattleObjectModuleAccessorEj");
        u64 detach_kind(app::BattleObjectModuleAccessor *,phx::Hash40,int) asm("_ZN3app8lua_bind30EffectModule__detach_kind_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40Ei");
        u64 detach(app::BattleObjectModuleAccessor *,unsigned int,int) asm("_ZN3app8lua_bind25EffectModule__detach_implEPNS_26BattleObjectModuleAccessorEji");
        u64 end_kind(app::BattleObjectModuleAccessor *,phx::Hash40,int) asm("_ZN3app8lua_bind27EffectModule__end_kind_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40Ei");
        u64 req_after_image(app::BattleObjectModuleAccessor *,phx::Hash40,phx::Hash40,phx::Hash40,phx::Hash40,unsigned int,phx::Vector3f const&,phx::Vector3f const&,unsigned int,phx::Hash40,phx::Hash40,phx::Vector3f const&,phx::Vector3f const&,float,unsigned char,unsigned char,float,int,int,int) asm("_ZN3app8lua_bind34EffectModule__req_after_image_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40ES4_S4_S4_jRKNS3_8Vector3fES7_jS4_S4_S7_S7_fhhfiii");
        u64 req_after_image_no_parent(app::BattleObjectModuleAccessor *,phx::Hash40,phx::Hash40,unsigned int,phx::Vector3f const&,phx::Vector3f const&,unsigned int,phx::Hash40,phx::Hash40,phx::Vector3f const&,phx::Vector3f const&,float,unsigned char,unsigned char,float,int,int,int) asm("_ZN3app8lua_bind44EffectModule__req_after_image_no_parent_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40ES4_jRKNS3_8Vector3fES7_jS4_S4_S7_S7_fhhfiii");
        u64 clear_all_after_image(app::BattleObjectModuleAccessor *,unsigned int) asm("_ZN3app8lua_bind40EffectModule__clear_all_after_image_implEPNS_26BattleObjectModuleAccessorEj");
        u64 remove_after_image(app::BattleObjectModuleAccessor *,unsigned int,unsigned int) asm("_ZN3app8lua_bind37EffectModule__remove_after_image_implEPNS_26BattleObjectModuleAccessorEjj");
        u64 remove_all_after_image(app::BattleObjectModuleAccessor *,unsigned int,unsigned int) asm("_ZN3app8lua_bind41EffectModule__remove_all_after_image_implEPNS_26BattleObjectModuleAccessorEjj");
        u64 get_local_matrix(app::BattleObjectModuleAccessor *,unsigned int) asm("_ZN3app8lua_bind35EffectModule__get_local_matrix_implEPNS_26BattleObjectModuleAccessorEj");
        void set_pos(app::BattleObjectModuleAccessor *,unsigned int,phx::Vector3f const&) asm("_ZN3app8lua_bind26EffectModule__set_pos_implEPNS_26BattleObjectModuleAccessorEjRKN3phx8Vector3fE");
        void set_rot(app::BattleObjectModuleAccessor *,unsigned int,phx::Vector3f const&) asm("_ZN3app8lua_bind26EffectModule__set_rot_implEPNS_26BattleObjectModuleAccessorEjRKN3phx8Vector3fE");
        void set_scale(app::BattleObjectModuleAccessor *,unsigned int,phx::Vector3f const&) asm("_ZN3app8lua_bind28EffectModule__set_scale_implEPNS_26BattleObjectModuleAccessorEjRKN3phx8Vector3fE");
        bool is_exist_effect(app::BattleObjectModuleAccessor *,unsigned int) asm("_ZN3app8lua_bind34EffectModule__is_exist_effect_implEPNS_26BattleObjectModuleAccessorEj");
        void set_visible(app::BattleObjectModuleAccessor *,unsigned int,bool) asm("_ZN3app8lua_bind30EffectModule__set_visible_implEPNS_26BattleObjectModuleAccessorEjb");
        void set_visible_kind(app::BattleObjectModuleAccessor *,phx::Hash40,bool) asm("_ZN3app8lua_bind35EffectModule__set_visible_kind_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40Eb");
        void set_whole(app::BattleObjectModuleAccessor *,bool) asm("_ZN3app8lua_bind28EffectModule__set_whole_implEPNS_26BattleObjectModuleAccessorEb");
        bool is_whole(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind27EffectModule__is_whole_implEPNS_26BattleObjectModuleAccessorE");
        void set_whole_attr(app::BattleObjectModuleAccessor *,bool,unsigned int) asm("_ZN3app8lua_bind33EffectModule__set_whole_attr_implEPNS_26BattleObjectModuleAccessorEbj");
        u64 fill_screen(app::BattleObjectModuleAccessor *,int,int,phx::Vector4f const&,app::EffectScreenBlendType,app::EffectScreenLayer,unsigned char) asm("_ZN3app8lua_bind30EffectModule__fill_screen_implEPNS_26BattleObjectModuleAccessorEiiRKN3phx8Vector4fENS_21EffectScreenBlendTypeENS_17EffectScreenLayerEh");
        u64 fill_screen_2(app::BattleObjectModuleAccessor *,int,int,phx::Vector4f const&,phx::Vector4f const&,float,float,app::EffectScreenLayer,unsigned char) asm("_ZN3app8lua_bind32EffectModule__fill_screen_2_implEPNS_26BattleObjectModuleAccessorEiiRKN3phx8Vector4fES6_ffNS_17EffectScreenLayerEh");
        u64 color_collection(app::BattleObjectModuleAccessor *,int,int,phx::Vector4f const&,phx::Vector4f const&,float,float,float,float,float,app::EffectScreenBlendType,unsigned char) asm("_ZN3app8lua_bind35EffectModule__color_collection_implEPNS_26BattleObjectModuleAccessorEiiRKN3phx8Vector4fES6_fffffNS_21EffectScreenBlendTypeEh");
        u64 clear_screen(app::BattleObjectModuleAccessor *,int,int) asm("_ZN3app8lua_bind31EffectModule__clear_screen_implEPNS_26BattleObjectModuleAccessorEii");
        u64 reset_screen(app::BattleObjectModuleAccessor *,int) asm("_ZN3app8lua_bind31EffectModule__reset_screen_implEPNS_26BattleObjectModuleAccessorEi");
        u64 get_dead_effect_rot_z(app::BattleObjectModuleAccessor *,phx::Vector3f const&,float,bool) asm("_ZN3app8lua_bind40EffectModule__get_dead_effect_rot_z_implEPNS_26BattleObjectModuleAccessorERKN3phx8Vector3fEfb");
        u64 get_dead_effect_scale(app::BattleObjectModuleAccessor *,phx::Vector3f const&,float,bool) asm("_ZN3app8lua_bind40EffectModule__get_dead_effect_scale_implEPNS_26BattleObjectModuleAccessorERKN3phx8Vector3fEfb");
        bool is_dead_effect_slant(app::BattleObjectModuleAccessor *,phx::Vector3f const&,float) asm("_ZN3app8lua_bind39EffectModule__is_dead_effect_slant_implEPNS_26BattleObjectModuleAccessorERKN3phx8Vector3fEf");
        u64 req_common(app::BattleObjectModuleAccessor *,phx::Hash40,float) asm("_ZN3app8lua_bind29EffectModule__req_common_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40Ef");
        u64 remove_common(app::BattleObjectModuleAccessor *,phx::Hash40) asm("_ZN3app8lua_bind32EffectModule__remove_common_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40E");
        u64 reset_common(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind31EffectModule__reset_common_implEPNS_26BattleObjectModuleAccessorE");
        bool is_end_common(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind32EffectModule__is_end_common_implEPNS_26BattleObjectModuleAccessorE");
        bool is_exist_common(app::BattleObjectModuleAccessor *,phx::Hash40) asm("_ZN3app8lua_bind34EffectModule__is_exist_common_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40E");
        u64 req_screen(app::BattleObjectModuleAccessor *,phx::Hash40,bool,bool,bool) asm("_ZN3app8lua_bind29EffectModule__req_screen_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40Ebbb");
        u64 req_screen_system(app::BattleObjectModuleAccessor *,phx::Hash40,bool,bool) asm("_ZN3app8lua_bind36EffectModule__req_screen_system_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40Ebb");
        u64 remove_screen(app::BattleObjectModuleAccessor *,phx::Hash40,int) asm("_ZN3app8lua_bind32EffectModule__remove_screen_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40Ei");
        void set_sync_visibility(app::BattleObjectModuleAccessor *,bool) asm("_ZN3app8lua_bind38EffectModule__set_sync_visibility_implEPNS_26BattleObjectModuleAccessorEb");
        bool is_sync_visibility(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind37EffectModule__is_sync_visibility_implEPNS_26BattleObjectModuleAccessorE");
        void set_sync_scale(app::BattleObjectModuleAccessor *,bool) asm("_ZN3app8lua_bind33EffectModule__set_sync_scale_implEPNS_26BattleObjectModuleAccessorEb");
        bool is_sync_scale(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind32EffectModule__is_sync_scale_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_variation_effect_kind(app::BattleObjectModuleAccessor *,phx::Hash40,int) asm("_ZN3app8lua_bind44EffectModule__get_variation_effect_kind_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40Ei");
        void set_rgb(app::BattleObjectModuleAccessor *,unsigned int,float,float,float) asm("_ZN3app8lua_bind26EffectModule__set_rgb_implEPNS_26BattleObjectModuleAccessorEjfff");
        void set_rgb_partial_last(app::BattleObjectModuleAccessor *,float,float,float) asm("_ZN3app8lua_bind39EffectModule__set_rgb_partial_last_implEPNS_26BattleObjectModuleAccessorEfff");
        void set_alpha(app::BattleObjectModuleAccessor *,unsigned int,float) asm("_ZN3app8lua_bind28EffectModule__set_alpha_implEPNS_26BattleObjectModuleAccessorEjf");
        void set_frame(app::BattleObjectModuleAccessor *,unsigned int,float) asm("_ZN3app8lua_bind28EffectModule__set_frame_implEPNS_26BattleObjectModuleAccessorEjf");
        void set_billboard(app::BattleObjectModuleAccessor *,unsigned int,bool) asm("_ZN3app8lua_bind32EffectModule__set_billboard_implEPNS_26BattleObjectModuleAccessorEjb");
        void set_rate(app::BattleObjectModuleAccessor *,unsigned int,float) asm("_ZN3app8lua_bind27EffectModule__set_rate_implEPNS_26BattleObjectModuleAccessorEjf");
        void set_rate_last(app::BattleObjectModuleAccessor *,float) asm("_ZN3app8lua_bind32EffectModule__set_rate_last_implEPNS_26BattleObjectModuleAccessorEf");
        void set_scale_last(app::BattleObjectModuleAccessor *,phx::Vector3f const&) asm("_ZN3app8lua_bind33EffectModule__set_scale_last_implEPNS_26BattleObjectModuleAccessorERKN3phx8Vector3fE");
        void set_alpha_last(app::BattleObjectModuleAccessor *,float) asm("_ZN3app8lua_bind33EffectModule__set_alpha_last_implEPNS_26BattleObjectModuleAccessorEf");
        void set_disable_system_slow(app::BattleObjectModuleAccessor *,bool) asm("_ZN3app8lua_bind42EffectModule__set_disable_system_slow_implEPNS_26BattleObjectModuleAccessorEb");
        void set_slow_rate_mul(app::BattleObjectModuleAccessor *,float) asm("_ZN3app8lua_bind36EffectModule__set_slow_rate_mul_implEPNS_26BattleObjectModuleAccessorEf");
        void set_slow_rate_no_stop_mul(app::BattleObjectModuleAccessor *,float) asm("_ZN3app8lua_bind44EffectModule__set_slow_rate_no_stop_mul_implEPNS_26BattleObjectModuleAccessorEf");
        void set_add_vel(app::BattleObjectModuleAccessor *,unsigned int,phx::Vector3f &) asm("_ZN3app8lua_bind30EffectModule__set_add_vel_implEPNS_26BattleObjectModuleAccessorEjRN3phx8Vector3fE");
        void set_material_anim_last(app::BattleObjectModuleAccessor *,int) asm("_ZN3app8lua_bind41EffectModule__set_material_anim_last_implEPNS_26BattleObjectModuleAccessorEi");
        void set_disable_render_offset_last(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind49EffectModule__set_disable_render_offset_last_implEPNS_26BattleObjectModuleAccessorE");
        u64 get_last_handle(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind34EffectModule__get_last_handle_implEPNS_26BattleObjectModuleAccessorE");
        bool is_enable_ground_effect(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind42EffectModule__is_enable_ground_effect_implEPNS_26BattleObjectModuleAccessorE");
        u64 kill_status_effect(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind37EffectModule__kill_status_effect_implEPNS_26BattleObjectModuleAccessorE");
        u64 unsync_vis_whole(app::BattleObjectModuleAccessor *,unsigned int) asm("_ZN3app8lua_bind35EffectModule__unsync_vis_whole_implEPNS_26BattleObjectModuleAccessorEj");
        u64 sync_visibility(app::BattleObjectModuleAccessor *,bool) asm("_ZN3app8lua_bind34EffectModule__sync_visibility_implEPNS_26BattleObjectModuleAccessorEb");
        void set_offset_to_next(app::BattleObjectModuleAccessor *,int) asm("_ZN3app8lua_bind37EffectModule__set_offset_to_next_implEPNS_26BattleObjectModuleAccessorEi");
        u64 make_offset_hash(app::BattleObjectModuleAccessor *,phx::Hash40,int) asm("_ZN3app8lua_bind35EffectModule__make_offset_hash_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40Ei");
        u64 preset_lifetime_rate_partial(app::BattleObjectModuleAccessor *,float) asm("_ZN3app8lua_bind47EffectModule__preset_lifetime_rate_partial_implEPNS_26BattleObjectModuleAccessorEf");
        u64 preset_curtail_emitter(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind41EffectModule__preset_curtail_emitter_implEPNS_26BattleObjectModuleAccessorE");
        u64 preset_limit_num(app::BattleObjectModuleAccessor *,int) asm("_ZN3app8lua_bind35EffectModule__preset_limit_num_implEPNS_26BattleObjectModuleAccessorEi");
        u64 enable_sync_init_pos_last(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind44EffectModule__enable_sync_init_pos_last_implEPNS_26BattleObjectModuleAccessorE");
        void set_custom_uv_offset(app::BattleObjectModuleAccessor *,unsigned int,phx::Vector2f const&,int) asm("_ZN3app8lua_bind39EffectModule__set_custom_uv_offset_implEPNS_26BattleObjectModuleAccessorEjRKN3phx8Vector2fEi");
        u64 remove_post_effect_line(app::BattleObjectModuleAccessor *,int,bool) asm("_ZN3app8lua_bind42EffectModule__remove_post_effect_line_implEPNS_26BattleObjectModuleAccessorEib");
        u64 request_post_effect_line_circle(app::BattleObjectModuleAccessor *,phx::Hash40,phx::Hash40,phx::Vector2f,phx::Vector3f,bool,float,float) asm("_ZN3app8lua_bind50EffectModule__request_post_effect_line_circle_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40ES4_NS3_8Vector2fENS3_8Vector3fEbff");
        void set_post_effect_line_circle_target(app::BattleObjectModuleAccessor *,phx::Hash40,phx::Vector2f,phx::Vector3f,bool) asm("_ZN3app8lua_bind53EffectModule__set_post_effect_line_circle_target_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40ENS3_8Vector2fENS3_8Vector3fEb");
        u64 request_post_effect_line_parallel_2d(app::BattleObjectModuleAccessor *,phx::Hash40,phx::Vector2f,phx::Vector2f,phx::Vector2f,phx::Vector2f,bool,float,float) asm("_ZN3app8lua_bind55EffectModule__request_post_effect_line_parallel_2d_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40ENS3_8Vector2fES5_S5_S5_bff");
        u64 enable_stencil(app::BattleObjectModuleAccessor *,bool) asm("_ZN3app8lua_bind33EffectModule__enable_stencil_implEPNS_26BattleObjectModuleAccessorEb");
        u64 force_update_common_effect(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind45EffectModule__force_update_common_effect_implEPNS_26BattleObjectModuleAccessorE");
    }
}
