#pragma once

#include "../../useful/useful.h"
namespace app::lua_bind {
    namespace LinkModule {
        u64 link(app::BattleObjectModuleAccessor *, int,unsigned int) asm("_ZN3app8lua_bind21LinkModule__link_implEPNS_26BattleObjectModuleAccessorEij") LINKABLE;
        u64 unlink_all(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind27LinkModule__unlink_all_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        u64 unlink_node(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind28LinkModule__unlink_node_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 unlink_node_all(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind32LinkModule__unlink_node_all_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        u64 unlink(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind23LinkModule__unlink_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        bool is_link(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind24LinkModule__is_link_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        bool is_linked(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind26LinkModule__is_linked_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 get_parent_id(app::BattleObjectModuleAccessor *, int,bool) asm("_ZN3app8lua_bind30LinkModule__get_parent_id_implEPNS_26BattleObjectModuleAccessorEib") LINKABLE;
        u64 search_parent(app::BattleObjectModuleAccessor *, unsigned int) asm("_ZN3app8lua_bind30LinkModule__search_parent_implEPNS_26BattleObjectModuleAccessorEj") LINKABLE;
        u64 search_parent_attr(app::BattleObjectModuleAccessor *, app::LinkAttribute) asm("_ZN3app8lua_bind35LinkModule__search_parent_attr_implEPNS_26BattleObjectModuleAccessorENS_13LinkAttributeE") LINKABLE;
        u64 search_node(app::BattleObjectModuleAccessor *, unsigned int) asm("_ZN3app8lua_bind28LinkModule__search_node_implEPNS_26BattleObjectModuleAccessorEj") LINKABLE;
        u64 send_event_parents(app::BattleObjectModuleAccessor *, int,u64) asm("_ZN3app8lua_bind35LinkModule__send_event_parents_implEPNS_26BattleObjectModuleAccessorEiN3phx6Hash40E") LINKABLE;
        u64 send_event_parents_struct(app::BattleObjectModuleAccessor *, int,app::LinkEvent &) asm("_ZN3app8lua_bind42LinkModule__send_event_parents_struct_implEPNS_26BattleObjectModuleAccessorEiRNS_9LinkEventE") LINKABLE;
        u64 send_event_nodes_struct(app::BattleObjectModuleAccessor *, int,app::LinkEvent &,unsigned int) asm("_ZN3app8lua_bind40LinkModule__send_event_nodes_struct_implEPNS_26BattleObjectModuleAccessorEiRNS_9LinkEventEj") LINKABLE;
        u64 send_event_nodes(app::BattleObjectModuleAccessor *, int,u64,unsigned int) asm("_ZN3app8lua_bind33LinkModule__send_event_nodes_implEPNS_26BattleObjectModuleAccessorEiN3phx6Hash40Ej") LINKABLE;
        u64 send_event_nodes_throw(app::BattleObjectModuleAccessor *, u64,u64,bool,int,int,int) asm("_ZN3app8lua_bind39LinkModule__send_event_nodes_throw_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40ES4_biii") LINKABLE;
        u64 get_node_object_id(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind35LinkModule__get_node_object_id_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        bool is_node_damage_reaction(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind40LinkModule__is_node_damage_reaction_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        bool is_node_damage_capture_cut(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind43LinkModule__is_node_damage_capture_cut_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 chk_link_stop(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind30LinkModule__chk_link_stop_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        bool is_valid_link_stop(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind35LinkModule__is_valid_link_stop_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        u64 chk_link_visibility(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind36LinkModule__chk_link_visibility_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        u64 get_link_scale(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind31LinkModule__get_link_scale_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        bool is_link_pos(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind28LinkModule__is_link_pos_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        u64 update_link_pos(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind32LinkModule__update_link_pos_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        u64 get_link_speed(app::BattleObjectModuleAccessor *, Vector2f &) asm("_ZN3app8lua_bind31LinkModule__get_link_speed_implEPNS_26BattleObjectModuleAccessorERN3phx8Vector2fE") LINKABLE;
        u64 get_parent_scale(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind33LinkModule__get_parent_scale_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 get_parent_model_joint_global_position(app::BattleObjectModuleAccessor *, int,u64,bool) asm("_ZN3app8lua_bind55LinkModule__get_parent_model_joint_global_position_implEPNS_26BattleObjectModuleAccessorEiN3phx6Hash40Eb") LINKABLE;
        u64 get_parent_model_joint_global_rotation(app::BattleObjectModuleAccessor *, int,u64,bool) asm("_ZN3app8lua_bind55LinkModule__get_parent_model_joint_global_rotation_implEPNS_26BattleObjectModuleAccessorEiN3phx6Hash40Eb") LINKABLE;
        u64 get_parent_motion_frame(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind40LinkModule__get_parent_motion_frame_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 get_parent_motion_whole_rate(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind45LinkModule__get_parent_motion_whole_rate_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 get_parent_motion_rate(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind39LinkModule__get_parent_motion_rate_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 get_parent_motion_kind(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind39LinkModule__get_parent_motion_kind_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 get_parent_situation_kind(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind42LinkModule__get_parent_situation_kind_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 get_parent_status_kind(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind39LinkModule__get_parent_status_kind_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 get_parent_lr(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind30LinkModule__get_parent_lr_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 get_parent_sum_speed(app::BattleObjectModuleAccessor *, int,int) asm("_ZN3app8lua_bind37LinkModule__get_parent_sum_speed_implEPNS_26BattleObjectModuleAccessorEii") LINKABLE;
        u64 get_parent_object_id(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind37LinkModule__get_parent_object_id_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        bool is_capture_damage_parent_object_id(app::BattleObjectModuleAccessor *, unsigned int) asm("_ZN3app8lua_bind51LinkModule__is_capture_damage_parent_object_id_implEPNS_26BattleObjectModuleAccessorEj") LINKABLE;
        u64 get_parent_pos(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind31LinkModule__get_parent_pos_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 get_parent_prev_pos(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind36LinkModule__get_parent_prev_pos_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 get_parent_rot(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind31LinkModule__get_parent_rot_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 get_parent_damage(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind34LinkModule__get_parent_damage_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 get_parent_damage_reaction(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind43LinkModule__get_parent_damage_reaction_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 get_parent_damage_power_max(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind44LinkModule__get_parent_damage_power_max_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 get_parent_top_angle(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind37LinkModule__get_parent_top_angle_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 set_node_scale_power_mul(app::BattleObjectModuleAccessor *, float) asm("_ZN3app8lua_bind41LinkModule__set_node_scale_power_mul_implEPNS_26BattleObjectModuleAccessorEf") LINKABLE;
        u64 set_node_link_scale(app::BattleObjectModuleAccessor *, float,bool) asm("_ZN3app8lua_bind36LinkModule__set_node_link_scale_implEPNS_26BattleObjectModuleAccessorEfb") LINKABLE;
        bool is_parent_damage_reaction(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind42LinkModule__is_parent_damage_reaction_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        bool is_parent_damage_catch_cut(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind43LinkModule__is_parent_damage_catch_cut_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 get_parent_total_hit_status(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind44LinkModule__get_parent_total_hit_status_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        bool is_valid_parent_shape(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind38LinkModule__is_valid_parent_shape_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 get_parent_shape_center_pos(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind44LinkModule__get_parent_shape_center_pos_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 get_parent_shape_center_pos_object_id(app::BattleObjectModuleAccessor *, unsigned int,Vector2f &) asm("_ZN3app8lua_bind54LinkModule__get_parent_shape_center_pos_object_id_implEPNS_26BattleObjectModuleAccessorEjRN3phx8Vector2fE") LINKABLE;
        bool is_parent_effect_sync_scale(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind44LinkModule__is_parent_effect_sync_scale_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        bool is_link_power_up(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind33LinkModule__is_link_power_up_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        u64 get_parent_power_up_attack(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind43LinkModule__get_parent_power_up_attack_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        u64 get_parent_power_up_defense(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind44LinkModule__get_parent_power_up_defense_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        u64 get_parent_power_up_attr(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind41LinkModule__get_parent_power_up_attr_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        u64 get_parent_customize_attack_ratio(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind50LinkModule__get_parent_customize_attack_ratio_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        bool is_link_node_attack(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind36LinkModule__is_link_node_attack_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        u64 get_parent_reaction_mul_4th(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind44LinkModule__get_parent_reaction_mul_4th_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        bool is_parent_power_up_reaction(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind44LinkModule__is_parent_power_up_reaction_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        u64 set_parent_hit_stop_frame(app::BattleObjectModuleAccessor *, int,int,bool) asm("_ZN3app8lua_bind42LinkModule__set_parent_hit_stop_frame_implEPNS_26BattleObjectModuleAccessorEiib") LINKABLE;
        u64 set_parent_attacker_info(app::BattleObjectModuleAccessor *, int,unsigned int) asm("_ZN3app8lua_bind41LinkModule__set_parent_attacker_info_implEPNS_26BattleObjectModuleAccessorEij") LINKABLE;
        u64 set_node_attacker_info(app::BattleObjectModuleAccessor *, int,unsigned int) asm("_ZN3app8lua_bind39LinkModule__set_node_attacker_info_implEPNS_26BattleObjectModuleAccessorEij") LINKABLE;
        u64 set_parent_log_damage_player(app::BattleObjectModuleAccessor *, int,unsigned int,int,int) asm("_ZN3app8lua_bind45LinkModule__set_parent_log_damage_player_implEPNS_26BattleObjectModuleAccessorEijii") LINKABLE;
        u64 set_node_log_damage_player(app::BattleObjectModuleAccessor *, int,unsigned int,int,int) asm("_ZN3app8lua_bind43LinkModule__set_node_log_damage_player_implEPNS_26BattleObjectModuleAccessorEijii") LINKABLE;
        u64 set_node_depth_offset(app::BattleObjectModuleAccessor *, int,float) asm("_ZN3app8lua_bind38LinkModule__set_node_depth_offset_implEPNS_26BattleObjectModuleAccessorEif") LINKABLE;
        u64 get_parent_have_item_visibility(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind48LinkModule__get_parent_have_item_visibility_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 get_parent_attach_item_visibility(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind50LinkModule__get_parent_attach_item_visibility_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 get_parent_main_color(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind38LinkModule__get_parent_main_color_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        bool is_parent_enable_sub_color(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind43LinkModule__is_parent_enable_sub_color_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 get_parent_sub_color(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind37LinkModule__get_parent_sub_color_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 get_parent_battle_object_kind(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind46LinkModule__get_parent_battle_object_kind_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 get_parent_object_id_motion_transactor_link(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind60LinkModule__get_parent_object_id_motion_transactor_link_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        u64 set_model_constraint_pos_ort(app::BattleObjectModuleAccessor *, int,u64,u64,unsigned int,bool) asm("_ZN3app8lua_bind45LinkModule__set_model_constraint_pos_ort_implEPNS_26BattleObjectModuleAccessorEiN3phx6Hash40ES4_jb") LINKABLE;
        u64 set_model_constraint_attribute(app::BattleObjectModuleAccessor *, int,bool) asm("_ZN3app8lua_bind47LinkModule__set_model_constraint_attribute_implEPNS_26BattleObjectModuleAccessorEib") LINKABLE;
        u64 get_model_constraint_flag(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind42LinkModule__get_model_constraint_flag_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        u64 set_model_constraint_flag(app::BattleObjectModuleAccessor *, unsigned int) asm("_ZN3app8lua_bind42LinkModule__set_model_constraint_flag_implEPNS_26BattleObjectModuleAccessorEj") LINKABLE;
        u64 off_model_constraint_flag(app::BattleObjectModuleAccessor *, unsigned int) asm("_ZN3app8lua_bind42LinkModule__off_model_constraint_flag_implEPNS_26BattleObjectModuleAccessorEj") LINKABLE;
        u64 get_model_constraint_joint(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind43LinkModule__get_model_constraint_joint_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        u64 get_model_constraint_target_joint(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind50LinkModule__get_model_constraint_target_joint_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        u64 set_model_constraint_joint(app::BattleObjectModuleAccessor *, u64) asm("_ZN3app8lua_bind43LinkModule__set_model_constraint_joint_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40E") LINKABLE;
        u64 set_model_constraint_target_joint(app::BattleObjectModuleAccessor *, u64) asm("_ZN3app8lua_bind50LinkModule__set_model_constraint_target_joint_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40E") LINKABLE;
        u64 get_model_constraint_no(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind40LinkModule__get_model_constraint_no_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        u64 adjust_model_constraint_posture(app::BattleObjectModuleAccessor *, Vector3f const*,Vector3f const*) asm("_ZN3app8lua_bind48LinkModule__adjust_model_constraint_posture_implEPNS_26BattleObjectModuleAccessorEPKN3phx8Vector3fES6_") LINKABLE;
        u64 remove_model_constraint(app::BattleObjectModuleAccessor *, bool) asm("_ZN3app8lua_bind40LinkModule__remove_model_constraint_implEPNS_26BattleObjectModuleAccessorEb") LINKABLE;
        bool is_model_constraint(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind36LinkModule__is_model_constraint_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        bool is_model_constraint_mutual(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind43LinkModule__is_model_constraint_mutual_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        u64 get_model_constraint_target_node_position(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind58LinkModule__get_model_constraint_target_node_position_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        u64 get_model_constraint_joint_global_position(app::BattleObjectModuleAccessor *, u64) asm("_ZN3app8lua_bind59LinkModule__get_model_constraint_joint_global_position_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40E") LINKABLE;
        u64 get_model_constraint_joint_global_position_recursive(app::BattleObjectModuleAccessor *, u64) asm("_ZN3app8lua_bind69LinkModule__get_model_constraint_joint_global_position_recursive_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40E") LINKABLE;
        u64 get_model_constraint_target_joint_rotation(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind59LinkModule__get_model_constraint_target_joint_rotation_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        u64 get_node_rotation(app::BattleObjectModuleAccessor *, int,u64,Vector3f &) asm("_ZN3app8lua_bind34LinkModule__get_node_rotation_implEPNS_26BattleObjectModuleAccessorEiN3phx6Hash40ERNS3_8Vector3fE") LINKABLE;
        u64 get_constraint_model_scale(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind43LinkModule__get_constraint_model_scale_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        u64 get_constraint_translate_offset(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind48LinkModule__get_constraint_translate_offset_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        bool is_change_model_constraint_matrix(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind50LinkModule__is_change_model_constraint_matrix_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        u64 set_attribute(app::BattleObjectModuleAccessor *, int,app::LinkAttribute,bool) asm("_ZN3app8lua_bind30LinkModule__set_attribute_implEPNS_26BattleObjectModuleAccessorEiNS_13LinkAttributeEb") LINKABLE;
        u64 chk_attribute(app::BattleObjectModuleAccessor *, int,app::LinkAttribute) asm("_ZN3app8lua_bind30LinkModule__chk_attribute_implEPNS_26BattleObjectModuleAccessorEiNS_13LinkAttributeE") LINKABLE;
        u64 chk_linked_attribute(app::BattleObjectModuleAccessor *, app::LinkAttribute) asm("_ZN3app8lua_bind37LinkModule__chk_linked_attribute_implEPNS_26BattleObjectModuleAccessorENS_13LinkAttributeE") LINKABLE;
        bool is_link_parent_slow(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind36LinkModule__is_link_parent_slow_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        bool is_parent_flip(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind31LinkModule__is_parent_flip_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        bool is_parent_hit_stop(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind35LinkModule__is_parent_hit_stop_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 get_parent_stick_x(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind35LinkModule__get_parent_stick_x_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 get_node_catprue_pos(app::BattleObjectModuleAccessor *, int,Vector3f &) asm("_ZN3app8lua_bind37LinkModule__get_node_catprue_pos_implEPNS_26BattleObjectModuleAccessorEiRN3phx8Vector3fE") LINKABLE;
        u64 get_node_sum_speed(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind35LinkModule__get_node_sum_speed_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 get_node_scale(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind31LinkModule__get_node_scale_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 set_constraint_rot_offset_x(app::BattleObjectModuleAccessor *, float) asm("_ZN3app8lua_bind44LinkModule__set_constraint_rot_offset_x_implEPNS_26BattleObjectModuleAccessorEf") LINKABLE;
        u64 set_constraint_rot_offset_y(app::BattleObjectModuleAccessor *, float) asm("_ZN3app8lua_bind44LinkModule__set_constraint_rot_offset_y_implEPNS_26BattleObjectModuleAccessorEf") LINKABLE;
        u64 set_constraint_rot_offset_z(app::BattleObjectModuleAccessor *, float) asm("_ZN3app8lua_bind44LinkModule__set_constraint_rot_offset_z_implEPNS_26BattleObjectModuleAccessorEf") LINKABLE;
        u64 set_constraint_rot_offset(app::BattleObjectModuleAccessor *, const Vector3f*) asm("_ZN3app8lua_bind42LinkModule__set_constraint_rot_offset_implEPNS_26BattleObjectModuleAccessorERKN3phx8Vector3fE") LINKABLE;
        u64 set_constraint_scale_offset(app::BattleObjectModuleAccessor *, const Vector3f*) asm("_ZN3app8lua_bind44LinkModule__set_constraint_scale_offset_implEPNS_26BattleObjectModuleAccessorERKN3phx8Vector3fE") LINKABLE;
        u64 set_constraint_translate_offset(app::BattleObjectModuleAccessor *, const Vector3f*) asm("_ZN3app8lua_bind48LinkModule__set_constraint_translate_offset_implEPNS_26BattleObjectModuleAccessorERKN3phx8Vector3fE") LINKABLE;
        u64 set_unreference_parent_scale(app::BattleObjectModuleAccessor *, bool) asm("_ZN3app8lua_bind45LinkModule__set_unreference_parent_scale_implEPNS_26BattleObjectModuleAccessorEb") LINKABLE;
        u64 model_constraint_node_top_z(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind44LinkModule__model_constraint_node_top_z_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        bool is_parent_spycloak(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind35LinkModule__is_parent_spycloak_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 get_parent_model_visible(app::BattleObjectModuleAccessor *, int) asm("_ZN3app8lua_bind41LinkModule__get_parent_model_visible_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
    }
}
