#pragma once

#include "../../useful/useful.h"
namespace app::lua_bind {
    namespace MotionModule {
        u64 change_motion(app::BattleObjectModuleAccessor *,phx::Hash40,float,float,bool,float,bool,bool) asm("_ZN3app8lua_bind32MotionModule__change_motion_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40Effbfbb");
        u64 change_motion_inherit_frame(app::BattleObjectModuleAccessor *,phx::Hash40,float,float,float,bool,bool) asm("_ZN3app8lua_bind46MotionModule__change_motion_inherit_frame_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40Efffbb");
        u64 change_motion_inherit_frame_keep_rate(app::BattleObjectModuleAccessor *,phx::Hash40,float,float,float) asm("_ZN3app8lua_bind56MotionModule__change_motion_inherit_frame_keep_rate_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40Efff");
        u64 change_motion_force_inherit_frame(app::BattleObjectModuleAccessor *,phx::Hash40,float,float,float) asm("_ZN3app8lua_bind52MotionModule__change_motion_force_inherit_frame_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40Efff");
        u64 change_motion_kind(app::BattleObjectModuleAccessor *,phx::Hash40) asm("_ZN3app8lua_bind37MotionModule__change_motion_kind_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40E");
        u64 add_motion_2nd(app::BattleObjectModuleAccessor *,phx::Hash40,float,float,bool,float) asm("_ZN3app8lua_bind33MotionModule__add_motion_2nd_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40Effbf");
        void set_weight(app::BattleObjectModuleAccessor *,float,bool) asm("_ZN3app8lua_bind29MotionModule__set_weight_implEPNS_26BattleObjectModuleAccessorEfb");
        void set_weight_rate(app::BattleObjectModuleAccessor *,float) asm("_ZN3app8lua_bind34MotionModule__set_weight_rate_implEPNS_26BattleObjectModuleAccessorEf");
        bool is_blend(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind27MotionModule__is_blend_implEPNS_26BattleObjectModuleAccessorE");
        u64 motion_kind(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind30MotionModule__motion_kind_implEPNS_26BattleObjectModuleAccessorE");
        u64 rate(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind23MotionModule__rate_implEPNS_26BattleObjectModuleAccessorE");
        void set_rate(app::BattleObjectModuleAccessor *,float) asm("_ZN3app8lua_bind27MotionModule__set_rate_implEPNS_26BattleObjectModuleAccessorEf");
        u64 rate_2nd(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind27MotionModule__rate_2nd_implEPNS_26BattleObjectModuleAccessorE");
        void set_rate_2nd(app::BattleObjectModuleAccessor *,float) asm("_ZN3app8lua_bind31MotionModule__set_rate_2nd_implEPNS_26BattleObjectModuleAccessorEf");
        u64 frame(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind24MotionModule__frame_implEPNS_26BattleObjectModuleAccessorE");
        u64 prev_frame(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind29MotionModule__prev_frame_implEPNS_26BattleObjectModuleAccessorE");
        void set_frame(app::BattleObjectModuleAccessor *,float,bool) asm("_ZN3app8lua_bind28MotionModule__set_frame_implEPNS_26BattleObjectModuleAccessorEfb");
        void set_frame_sync_anim_cmd(app::BattleObjectModuleAccessor *,float,bool,bool,bool) asm("_ZN3app8lua_bind42MotionModule__set_frame_sync_anim_cmd_implEPNS_26BattleObjectModuleAccessorEfbbb");
        u64 end_frame(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind28MotionModule__end_frame_implEPNS_26BattleObjectModuleAccessorE");
        u64 end_frame_from_hash(app::BattleObjectModuleAccessor *,phx::Hash40) asm("_ZN3app8lua_bind38MotionModule__end_frame_from_hash_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40E");
        void set_frame_2nd(app::BattleObjectModuleAccessor *,float,bool) asm("_ZN3app8lua_bind32MotionModule__set_frame_2nd_implEPNS_26BattleObjectModuleAccessorEfb");
        u64 frame_2nd(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind28MotionModule__frame_2nd_implEPNS_26BattleObjectModuleAccessorE");
        u64 trans_tra(app::BattleObjectModuleAccessor *,phx::Vector3f &,bool,bool) asm("_ZN3app8lua_bind28MotionModule__trans_tra_implEPNS_26BattleObjectModuleAccessorERN3phx8Vector3fEbb");
        u64 trans_tra_2nd(app::BattleObjectModuleAccessor *,phx::Vector3f &,bool,bool) asm("_ZN3app8lua_bind32MotionModule__trans_tra_2nd_implEPNS_26BattleObjectModuleAccessorERN3phx8Vector3fEbb");
        u64 joint_local_tra(app::BattleObjectModuleAccessor *,phx::Hash40,bool,phx::Vector3f &) asm("_ZN3app8lua_bind34MotionModule__joint_local_tra_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40EbRNS3_8Vector3fE");
        u64 trans_tra_end_frame(app::BattleObjectModuleAccessor *,phx::Hash40,phx::Vector3f &) asm("_ZN3app8lua_bind38MotionModule__trans_tra_end_frame_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40ERNS3_8Vector3fE");
        bool is_end(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind25MotionModule__is_end_implEPNS_26BattleObjectModuleAccessorE");
        bool is_looped(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind28MotionModule__is_looped_implEPNS_26BattleObjectModuleAccessorE");
        bool is_loop_flag(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind31MotionModule__is_loop_flag_implEPNS_26BattleObjectModuleAccessorE");
        u64 update_trans_move_speed(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind42MotionModule__update_trans_move_speed_implEPNS_26BattleObjectModuleAccessorE");
        u64 trans_move_speed(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind35MotionModule__trans_move_speed_implEPNS_26BattleObjectModuleAccessorE");
        u64 trans_move_speed_2nd(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind39MotionModule__trans_move_speed_2nd_implEPNS_26BattleObjectModuleAccessorE");
        void set_trans_move_speed_no_scale(app::BattleObjectModuleAccessor *,bool) asm("_ZN3app8lua_bind48MotionModule__set_trans_move_speed_no_scale_implEPNS_26BattleObjectModuleAccessorEb");
        bool is_anim_resource(app::BattleObjectModuleAccessor *,phx::Hash40) asm("_ZN3app8lua_bind35MotionModule__is_anim_resource_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40E");
        u64 resource_id(app::BattleObjectModuleAccessor *,phx::Hash40) asm("_ZN3app8lua_bind30MotionModule__resource_id_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40E");
        u64 animcmd_name_hash(app::BattleObjectModuleAccessor *,phx::Hash40) asm("_ZN3app8lua_bind36MotionModule__animcmd_name_hash_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40E");
        u64 weight(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind25MotionModule__weight_implEPNS_26BattleObjectModuleAccessorE");
        u64 prev_weight(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind30MotionModule__prev_weight_implEPNS_26BattleObjectModuleAccessorE");
        void set_weight_change_motion(app::BattleObjectModuleAccessor *,float) asm("_ZN3app8lua_bind43MotionModule__set_weight_change_motion_implEPNS_26BattleObjectModuleAccessorEf");
        u64 calc_joint(app::BattleObjectModuleAccessor *,phx::Hash40,phx::Hash40,phx::Vector3f &) asm("_ZN3app8lua_bind29MotionModule__calc_joint_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40ES4_RNS3_8Vector3fE");
        u64 update_dynamic_skeleton_without_complete_matrix(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind66MotionModule__update_dynamic_skeleton_without_complete_matrix_implEPNS_26BattleObjectModuleAccessorE");
        u64 joint_local_rotation(app::BattleObjectModuleAccessor *,phx::Hash40,phx::Vector3f &) asm("_ZN3app8lua_bind39MotionModule__joint_local_rotation_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40ERNS3_8Vector3fE");
        void set_trans_joint_id(app::BattleObjectModuleAccessor *,phx::Hash40) asm("_ZN3app8lua_bind37MotionModule__set_trans_joint_id_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40E");
        u64 end_frame_2nd(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind32MotionModule__end_frame_2nd_implEPNS_26BattleObjectModuleAccessorE");
        bool is_end_2nd(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind29MotionModule__is_end_2nd_implEPNS_26BattleObjectModuleAccessorE");
        u64 motion_kind_2nd(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind34MotionModule__motion_kind_2nd_implEPNS_26BattleObjectModuleAccessorE");
        bool is_flag_link(app::BattleObjectModuleAccessor *,phx::Hash40) asm("_ZN3app8lua_bind31MotionModule__is_flag_link_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40E");
        bool is_flag_start_1_frame_from_motion_kind(app::BattleObjectModuleAccessor *,phx::Hash40) asm("_ZN3app8lua_bind57MotionModule__is_flag_start_1_frame_from_motion_kind_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40E");
        bool is_flag_start_1_frame(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind40MotionModule__is_flag_start_1_frame_implEPNS_26BattleObjectModuleAccessorE");
        bool is_flag_start_1_frame_2nd(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind44MotionModule__is_flag_start_1_frame_2nd_implEPNS_26BattleObjectModuleAccessorE");
        u64 joint_rotate(app::BattleObjectModuleAccessor *,phx::Hash40,phx::Vector3f &) asm("_ZN3app8lua_bind31MotionModule__joint_rotate_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40ERNS3_8Vector3fE");
        u64 add_motion_partial(app::BattleObjectModuleAccessor *,int,phx::Hash40,float,float,bool,bool,float,bool,bool,bool) asm("_ZN3app8lua_bind37MotionModule__add_motion_partial_implEPNS_26BattleObjectModuleAccessorEiN3phx6Hash40Effbbfbbb");
        u64 remove_motion_partial(app::BattleObjectModuleAccessor *,int,bool) asm("_ZN3app8lua_bind40MotionModule__remove_motion_partial_implEPNS_26BattleObjectModuleAccessorEib");
        u64 remove_motion_partial_comp(app::BattleObjectModuleAccessor *,int) asm("_ZN3app8lua_bind45MotionModule__remove_motion_partial_comp_implEPNS_26BattleObjectModuleAccessorEi");
        u64 motion_kind_partial(app::BattleObjectModuleAccessor *,int) asm("_ZN3app8lua_bind38MotionModule__motion_kind_partial_implEPNS_26BattleObjectModuleAccessorEi");
        bool is_end_partial(app::BattleObjectModuleAccessor *,int) asm("_ZN3app8lua_bind33MotionModule__is_end_partial_implEPNS_26BattleObjectModuleAccessorEi");
        u64 end_frame_partial(app::BattleObjectModuleAccessor *,int) asm("_ZN3app8lua_bind36MotionModule__end_frame_partial_implEPNS_26BattleObjectModuleAccessorEi");
        void set_rate_partial(app::BattleObjectModuleAccessor *,int,float) asm("_ZN3app8lua_bind35MotionModule__set_rate_partial_implEPNS_26BattleObjectModuleAccessorEif");
        u64 rate_partial(app::BattleObjectModuleAccessor *,int) asm("_ZN3app8lua_bind31MotionModule__rate_partial_implEPNS_26BattleObjectModuleAccessorEi");
        u64 frame_partial(app::BattleObjectModuleAccessor *,int) asm("_ZN3app8lua_bind32MotionModule__frame_partial_implEPNS_26BattleObjectModuleAccessorEi");
        u64 prev_frame_partial(app::BattleObjectModuleAccessor *,int) asm("_ZN3app8lua_bind37MotionModule__prev_frame_partial_implEPNS_26BattleObjectModuleAccessorEi");
        void set_frame_partial(app::BattleObjectModuleAccessor *,int,float,bool) asm("_ZN3app8lua_bind36MotionModule__set_frame_partial_implEPNS_26BattleObjectModuleAccessorEifb");
        void set_frame_partial_sync_anim_cmd(app::BattleObjectModuleAccessor *,int,float,bool) asm("_ZN3app8lua_bind50MotionModule__set_frame_partial_sync_anim_cmd_implEPNS_26BattleObjectModuleAccessorEifb");
        bool is_flag_start_1_frame_partial(app::BattleObjectModuleAccessor *,int) asm("_ZN3app8lua_bind48MotionModule__is_flag_start_1_frame_partial_implEPNS_26BattleObjectModuleAccessorEi");
        bool is_flip(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind26MotionModule__is_flip_implEPNS_26BattleObjectModuleAccessorE");
        void set_flip(app::BattleObjectModuleAccessor *,bool,bool,bool) asm("_ZN3app8lua_bind27MotionModule__set_flip_implEPNS_26BattleObjectModuleAccessorEbbb");
        void set_link_flip_target_joint(app::BattleObjectModuleAccessor *,bool) asm("_ZN3app8lua_bind45MotionModule__set_link_flip_target_joint_implEPNS_26BattleObjectModuleAccessorEb");
        void set_frame_material(app::BattleObjectModuleAccessor *,float,app::MaterialAnimeKind) asm("_ZN3app8lua_bind37MotionModule__set_frame_material_implEPNS_26BattleObjectModuleAccessorEfNS_17MaterialAnimeKindE");
        void set_rate_material(app::BattleObjectModuleAccessor *,float,app::MaterialAnimeKind) asm("_ZN3app8lua_bind36MotionModule__set_rate_material_implEPNS_26BattleObjectModuleAccessorEfNS_17MaterialAnimeKindE");
        void set_loop_flag_material(app::BattleObjectModuleAccessor *,app::MaterialAnimeLoopFlag,app::MaterialAnimeKind) asm("_ZN3app8lua_bind41MotionModule__set_loop_flag_material_implEPNS_26BattleObjectModuleAccessorENS_21MaterialAnimeLoopFlagENS_17MaterialAnimeKindE");
        u64 get_frame_material(app::BattleObjectModuleAccessor *,app::MaterialAnimeKind) asm("_ZN3app8lua_bind37MotionModule__get_frame_material_implEPNS_26BattleObjectModuleAccessorENS_17MaterialAnimeKindE");
        void set_helper_calculation(app::BattleObjectModuleAccessor *,bool) asm("_ZN3app8lua_bind41MotionModule__set_helper_calculation_implEPNS_26BattleObjectModuleAccessorEb");
        void set_skip_rate(app::BattleObjectModuleAccessor *,float,bool) asm("_ZN3app8lua_bind32MotionModule__set_skip_rate_implEPNS_26BattleObjectModuleAccessorEfb");
        u64 whole_rate(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind29MotionModule__whole_rate_implEPNS_26BattleObjectModuleAccessorE");
        void set_whole_rate(app::BattleObjectModuleAccessor *,float) asm("_ZN3app8lua_bind33MotionModule__set_whole_rate_implEPNS_26BattleObjectModuleAccessorEf");
        u64 update_rate(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind30MotionModule__update_rate_implEPNS_26BattleObjectModuleAccessorE");
        void set_recalc_ik(app::BattleObjectModuleAccessor *,bool) asm("_ZN3app8lua_bind32MotionModule__set_recalc_ik_implEPNS_26BattleObjectModuleAccessorEb");
        void set_no_comp(app::BattleObjectModuleAccessor *,bool) asm("_ZN3app8lua_bind30MotionModule__set_no_comp_implEPNS_26BattleObjectModuleAccessorEb");
        bool is_no_comp(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind29MotionModule__is_no_comp_implEPNS_26BattleObjectModuleAccessorE");
        void set_kind_offset(app::BattleObjectModuleAccessor *,int) asm("_ZN3app8lua_bind34MotionModule__set_kind_offset_implEPNS_26BattleObjectModuleAccessorEi");
        u64 enable_shift_material_animation(app::BattleObjectModuleAccessor *,bool) asm("_ZN3app8lua_bind50MotionModule__enable_shift_material_animation_implEPNS_26BattleObjectModuleAccessorEb");
        u64 trans_joint_scale(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind36MotionModule__trans_joint_scale_implEPNS_26BattleObjectModuleAccessorE");
        void set_stop_interpolation(app::BattleObjectModuleAccessor *,float,bool) asm("_ZN3app8lua_bind41MotionModule__set_stop_interpolation_implEPNS_26BattleObjectModuleAccessorEfb");
        bool is_flip_resource(app::BattleObjectModuleAccessor *) asm("_ZN3app8lua_bind35MotionModule__is_flip_resource_implEPNS_26BattleObjectModuleAccessorE");
        void set_reverse(app::BattleObjectModuleAccessor *,bool) asm("_ZN3app8lua_bind30MotionModule__set_reverse_implEPNS_26BattleObjectModuleAccessorEb");
        void set_force_progress_2nd_weight(app::BattleObjectModuleAccessor *,bool) asm("_ZN3app8lua_bind48MotionModule__set_force_progress_2nd_weight_implEPNS_26BattleObjectModuleAccessorEb");
        u64 clear_joint_srt(app::BattleObjectModuleAccessor *,phx::Hash40) asm("_ZN3app8lua_bind34MotionModule__clear_joint_srt_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40E");
        u64 start_flip_interpolation(app::BattleObjectModuleAccessor *,bool,int) asm("_ZN3app8lua_bind43MotionModule__start_flip_interpolation_implEPNS_26BattleObjectModuleAccessorEbi");
    }
}
